<?php
/*
Plugin Name: What is today?
Plugin URI: 
Description: 今日は何の日？ふっふー
Version: 1.0.0
Author:chikage
Author URI: http://aqours.tokyo
License: GPL2
*/

/*  Copyright 2017 chikage (email : whatistoday@aqours.tokyo)
 
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as
     published by the Free Software Foundation.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

function what_is_today() {
    switch (intval(date_i18n("m"))) {
    	case 1:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "元日";
    	        case 2:
    	            return "書初め";
    	        case 3:
    	            return "瞳の日";
    	        case 4:
    	            return "大発会";
    	        case 5:
    	            return "囲碁の日";
    	        case 6:
    	            return "色の日";
    	        case 7:
    	            return "七草の日";
    	        case 8:
    	            return "外国郵便の日";
    	        case 9:
    	            return "クイズの日";
    	        case 10:
    	            return "明太子の日";
    	        case 11:
    	            return "塩の日";
    	        case 12:
    	            return "スキー記念日";
    	        case 13:
    	            return "たばこの日";
    	        case 14:
    	            return "尖閣諸島開拓の日";
    	        case 15:
    	            return "いちごの日";
    	        case 16:
    	            return "禁酒の日";
    	        case 17:
    	            return "おむすびの日";
    	        case 18:
    	            return "118番の日";
    	        case 19:
    	            return "カラオケの日";
    	        case 20:
    	            return "玉の輿の日";
    	        case 21:
    	            return "料理番組の日";
    	        case 22:
    	            return "カレーの日";
    	        case 23:
    	            return "電子メールの日";
    	        case 24:
    	            return "金の日";
    	        case 25:
    	            return "美容記念日";
    	        case 26:
    	            return "有料駐車場の日";
    	        case 27:
    	            return "求婚の日";
    	        case 28:
    	            return "コピーライターの日";
    	        case 29:
    	            return "人口調査記念日";
    	        case 30:
    	            return "世界初のコンピューターウィルスが作成された日";
    	        case 31:
    	            return "生命保険の日";
    	    }
    	    break;
    	case 2:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "テレビ放送記念日";
    	        case 2:
    	            return "情報セキュリティの日";
    	        case 3:
    	            return "大豆の日";
    	        case 4:
    	            return "西の日";
    	        case 5:
    	            return "笑顔の日";
    	        case 6:
    	            return "抹茶の日";
    	        case 7:
    	            return "北方領土の日";
    	        case 8:
    	            return "郵便マークの日";
    	        case 9:
    	            return "漫画の日";
    	        case 10:
    	            return "ふとんの日";
    	        case 11:
    	            return "建国記念の日";
    	        case 12:
    	            return "ブラジャーの日";
    	        case 13:
    	            return "苗字制定記念日";
    	        case 14:
    	            return "バレンタインデー";
    	        case 15:
    	            return "春一番名付けの日";
    	        case 16:
    	            return "寒天の日";
    	        case 17:
    	            return "天使のささやきの日";
    	        case 18:
    	            return "エアメールの日";
    	        case 19:
    	            return "プロレスの日";
    	        case 20:
    	            return "歌舞伎の日";
    	        case 21:
    	            return "日刊新聞創刊の日";
    	        case 22:
    	            return "猫の日";
    	        case 23:
    	            return "富士山の日";
    	        case 24:
    	            return "クロスカントリーの日";
    	        case 25:
    	            return "夕刊紙の日";
    	        case 26:
    	            return "脱出の日";
    	        case 27:
    	            return "冬の恋人の日";
    	        case 28:
    	            return "ビスケットの日";
    	        case 29:
    	            return "ニンニクの日";
    	    }
    	    break;
    	case 3:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "マヨネーズの日";
    	        case 2:
    	            return "ミニの日";
    	        case 3:
    	            return "雛祭り";
    	        case 4:
    	            return "バウムクーヘンの日";
    	        case 5:
    	            return "珊瑚の日";
    	        case 6:
    	            return "弟の日";
    	        case 7:
    	            return "サウナの日";
    	        case 8:
    	            return "みつばちの日";
    	        case 9:
    	            return "記念切手記念日";
    	        case 10:
    	            return "サボテンの日";
    	        case 11:
    	            return "東日本大震災発生日";
    	        case 12:
    	            return "サイフの日";
    	        case 13:
    	            return "サンドイッチデー";
    	        case 14:
    	            return "数学の日";
    	        case 15:
    	            return "サイコの日";
    	        case 16:
    	            return "財務の日";
    	        case 17:
    	            return "漫画週刊誌の日";
    	        case 18:
    	            return "点字ブロックの日";
    	        case 19:
    	            return "ミュージックの日";
    	        case 20:
    	            return "電卓の日";
    	        case 21:
    	            return "ランドセルの日";
    	        case 22:
    	            return "放送記念日";
    	        case 23:
    	            return "世界気象機関設立日";
    	        case 24:
    	            return "世界結核デー";
    	        case 25:
    	            return "電気記念日";
    	        case 26:
    	            return "カチューシャの唄の日";
    	        case 27:
    	            return "さくらの日";
    	        case 28:
    	            return "教師の日";
    	        case 29:
    	            return "マリモの日";
    	        case 30:
    	            return "マフィアの日";
    	        case 31:
    	            return "オーケストラの日";
    	    }
    	    break;
    	case 4:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "エイプリルフール";
    	        case 2:
    	            return "週刊誌の日";
    	        case 3:
    	            return "いんげん豆の日";
    	        case 4:
    	            return "ピアノ調律の日";
    	        case 5:
    	            return "ヘアカットの日";
    	        case 6:
    	            return "城の日";
    	        case 7:
    	            return "世界保健デー";
    	        case 8:
    	            return "忠犬ハチ公の日";
    	        case 9:
    	            return "大仏の日";
    	        case 10:
    	            return "ヨットの日";
    	        case 11:
    	            return "ガッツポーズの日";
    	        case 12:
    	            return "パンの記念日";
    	        case 13:
    	            return "喫茶店の日";
    	        case 14:
    	            return "椅子の日";
    	        case 15:
    	            return "ヘリコプターの日";
    	        case 16:
    	            return "チャップリンデー";
    	        case 17:
    	            return "なすび記念日";
    	        case 18:
    	            return "発明の日";
    	        case 19:
    	            return "地図の日";
    	        case 20:
    	            return "郵政記念日";
    	        case 21:
    	            return "民放の日";
    	        case 22:
    	            return "よい夫婦の日";
    	        case 23:
    	            return "地ビールの日";
    	        case 24:
    	            return "植物学の日";
    	        case 25:
    	            return "DNAの日";
    	        case 26:
    	            return "よい風呂の日";
    	        case 27:
    	            return "哲学の日";
    	        case 28:
    	            return "サンフランシスコ講和記念日";
    	        case 29:
    	            return "昭和の日";
    	        case 30:
    	            return "図書館記念日";
    	    }
    	    break;
    	case 5:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "すずらんの日";
    	        case 2:
    	            return "交通広告の日";
    	        case 3:
    	            return "憲法記念日";
    	        case 4:
    	            return "みどりの日";
    	        case 5:
    	            return "こどもの日";
    	        case 6:
    	            return "迷路の日";
    	        case 7:
    	            return "博士の日";
    	        case 8:
    	            return "松の日";
    	        case 9:
    	            return "黒板の日";
    	        case 10:
    	            return "コットンの日";
    	        case 11:
    	            return "コンピューターがチェスで世界チャンピオンに勝利した日";
    	        case 12:
    	            return "アセロラの日";
    	        case 13:
    	            return "カクテルの日";
    	        case 14:
    	            return "温度計の日";
    	        case 15:
    	            return "ヨーグルトの日";
    	        case 16:
    	            return "旅の日";
    	        case 17:
    	            return "世界高血圧デー";
    	        case 18:
    	            return "国際博物館の日";
    	        case 19:
    	            return "ボクシングの日";
    	        case 20:
    	            return "ローマ字の日";
    	        case 21:
    	            return "小学校の日";
    	        case 22:
    	            return "サイクリングの日";
    	        case 23:
    	            return "キスの日";
    	        case 24:
    	            return "ゴルフ場記念日";
    	        case 25:
    	            return "プリンの日";
    	        case 26:
    	            return "東名高速道路全通記念日";
    	        case 27:
    	            return "小松菜の日";
    	        case 28:
    	            return "花火の日";
    	        case 29:
    	            return "こんにゃくの日";
    	        case 30:
    	            return "掃除機の日";
    	        case 31:
    	            return "世界禁煙デー";
    	    }
    	    break;
    	case 6:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "写真の日";
    	        case 2:
    	            return "イタリアワインの日";
    	        case 3:
    	            return "測量の日";
    	        case 4:
    	            return "虫の日";
    	        case 5:
    	            return "落語の日";
    	        case 6:
    	            return "楽器の日";
    	        case 7:
    	            return "むち打ち治療の日";
    	        case 8:
    	            return "ヴァイキングの日";
    	        case 9:
    	            return "ロックの日";
    	        case 10:
    	            return "路面電車の日";
    	        case 11:
    	            return "傘の日";
    	        case 12:
    	            return "日記の日";
    	        case 13:
    	            return "FMの日";
    	        case 14:
    	            return "手羽先記念日";
    	        case 15:
    	            return "信用金庫の日";
    	        case 16:
    	            return "和菓子の日";
    	        case 17:
    	            return "臓器移植法成立日";
    	        case 18:
    	            return "海外移住の日";
    	        case 19:
    	            return "ロマンスの日";
    	        case 20:
    	            return "ペパーミントの日";
    	        case 21:
    	            return "冷蔵庫の日";
    	        case 22:
    	            return "かにの日";
    	        case 23:
    	            return "慰霊の日";
    	        case 24:
    	            return "UFO記念日";
    	        case 25:
    	            return "住宅デー";
    	        case 26:
    	            return "露天風呂の日";
    	        case 27:
    	            return "演説の日";
    	        case 28:
    	            return "パフェの日";
    	        case 29:
    	            return "佃煮の日";
    	        case 30:
    	            return "トランジスタの日";
    	    }
    	    break;
    	case 7:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "銀行の日";
    	        case 2:
    	            return "たわしの日";
    	        case 3:
    	            return "ソフトクリームの日";
    	        case 4:
    	            return "梨の日";
    	        case 5:
    	            return "穴子の日";
    	        case 6:
    	            return "ピアノの日";
    	        case 7:
    	            return "七夕";
    	        case 8:
    	            return "中国茶の日";
    	        case 9:
    	            return "ジェットコースターの日";
    	        case 10:
    	            return "納豆の日";
    	        case 11:
    	            return "職業教育の日";
    	        case 12:
    	            return "洋食器の日";
    	        case 13:
    	            return "オカルト記念日";
    	        case 14:
    	            return "ひまわりの日";
    	        case 15:
    	            return "マンゴーの日";
    	        case 16:
    	            return "駅弁記念日";
    	        case 17:
    	            return "東京の日";
    	        case 18:
    	            return "光化学スモッグの日";
    	        case 19:
    	            return "女性大臣の日";
    	        case 20:
    	            return "ハンバーガーの日";
    	        case 21:
    	            return "自然公園の日";
    	        case 22:
    	            return "下駄の日";
    	        case 23:
    	            return "カシスの日";
    	        case 24:
    	            return "劇画の日";
    	        case 25:
    	            return "かき氷の日";
    	        case 26:
    	            return "幽霊の日";
    	        case 27:
    	            return "スイカの日";
    	        case 28:
    	            return "地名の日";
    	        case 29:
    	            return "アマチュア無線の日";
    	        case 30:
    	            return "梅干の日";
    	        case 31:
    	            return "蓄音機の日";
    	    }
    	    break;
    	case 8:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "花火の日";
    	        case 2:
    	            return "カレーうどんの日";
    	        case 3:
    	            return "ハチミツの日";
    	        case 4:
    	            return "ビヤホールの日";
    	        case 5:
    	            return "タクシーの日";
    	        case 6:
    	            return "雨水の日";
    	        case 7:
    	            return "バナナの日";
    	        case 8:
    	            return "そろばんの日";
    	        case 9:
    	            return "野球の日";
    	        case 10:
    	            return "道の日";
    	        case 11:
    	            return "山の日";
    	        case 12:
    	            return "君が代記念日";
    	        case 13:
    	            return "函館夜景の日";
    	        case 14:
    	            return "専売特許の日";
    	        case 15:
    	            return "刺身の日";
    	        case 16:
    	            return "女子大生の日";
    	        case 17:
    	            return "パイナップルの日";
    	        case 18:
    	            return "米の日";
    	        case 19:
    	            return "バイクの日";
    	        case 20:
    	            return "蚊の日";
    	        case 21:
    	            return "噴水の日";
    	        case 22:
    	            return "チンチン電車の日";
    	        case 23:
    	            return "白虎隊の日";
    	        case 24:
    	            return "愛酒の日";
    	        case 25:
    	            return "川柳発祥の日";
    	        case 26:
    	            return "ナミビアの日";
    	        case 27:
    	            return "男はつらいよの日";
    	        case 28:
    	            return "民放テレビスタートの日";
    	        case 29:
    	            return "焼き肉の日";
    	        case 30:
    	            return "ハッピーサンシャインデー";
    	        case 31:
    	            return "野菜の日";
    	    }
    	    break;
    	case 9:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "キウイの日";
    	        case 2:
    	            return "宝くじの日";
    	        case 3:
    	            return "ベッドの日";
    	        case 4:
    	            return "クラシック音楽の日";
    	        case 5:
    	            return "石炭の日";
    	        case 6:
    	            return "妹の日";
    	        case 7:
    	            return "ブラジル独立記念日";
    	        case 8:
    	            return "聖母マリア誕生日";
    	        case 9:
    	            return "世界占いの日";
    	        case 10:
    	            return "牛タンの日";
    	        case 11:
    	            return "警察相談の日";
    	        case 12:
    	            return "宇宙の日";
    	        case 13:
    	            return "世界の法の日";
    	        case 14:
    	            return "セプテンバーバレンタイン";
    	        case 15:
    	            return "ひじきの日";
    	        case 16:
    	            return "ハイビジョンの日";
    	        case 17:
    	            return "イタリア料理の日";
    	        case 18:
    	            return "かいわれ大根の日";
    	        case 19:
    	            return "世界海賊口調日";
    	        case 20:
    	            return "バスの日";
    	        case 21:
    	            return "ファッションショーの日";
    	        case 22:
    	            return "世界サイの日";
    	        case 23:
    	            return "テニスの日";
    	        case 24:
    	            return "清掃の日";
    	        case 25:
    	            return "介護の日";
    	        case 26:
    	            return "ワープロ記念日";
    	        case 27:
    	            return "女性ドライバーの日";
    	        case 28:
    	            return "パソコン記念日";
    	        case 29:
    	            return "招き猫の日";
    	        case 30:
    	            return "クレーンの日";
    	    }
    	    break;
    	case 10:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "ネクタイの日";
    	        case 2:
    	            return "豆腐の日";
    	        case 3:
    	            return "登山の日";
    	        case 4:
    	            return "天使の日";
    	        case 5:
    	            return "レモンの日";
    	        case 6:
    	            return "国際協力の日";
    	        case 7:
    	            return "ミステリー記念日";
    	        case 8:
    	            return "FXの日";
    	        case 9:
    	            return "塾の日";
    	        case 10:
    	            return "貯金箱の日";
    	        case 11:
    	            return "ウインクの日";
    	        case 12:
    	            return "豆乳の日";
    	        case 13:
    	            return "サツマイモの日";
    	        case 14:
    	            return "鉄道の日";
    	        case 15:
    	            return "人形の日";
    	        case 16:
    	            return "ボスの日";
    	        case 17:
    	            return "カラオケ文化の日";
    	        case 18:
    	            return "ミニスカートの日";
    	        case 19:
    	            return "海外旅行の日";
    	        case 20:
    	            return "リサイクルの日";
    	        case 21:
    	            return "あかりの日";
    	        case 22:
    	            return "パラシュートの日";
    	        case 23:
    	            return "電信電話記念日";
    	        case 24:
    	            return "マーガリンの日";
    	        case 25:
    	            return "産業観光の日";
    	        case 26:
    	            return "柿の日";
    	        case 27:
    	            return "テディベアズ・デー";
    	        case 28:
    	            return "速記記念日";
    	        case 29:
    	            return "おしぼりの日";
    	        case 30:
    	            return "初恋の日";
    	        case 31:
    	            return "ハロウィン";
    	    }
    	    break;
    	case 11:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "犬の日";
    	        case 2:
    	            return "死者の日";
    	        case 3:
    	            return "文化の日";
    	        case 4:
    	            return "ユネスコ憲章記念日";
    	        case 5:
    	            return "津波防災の日";
    	        case 6:
    	            return "アパート記念日";
    	        case 7:
    	            return "鍋の日";
    	        case 8:
    	            return "ボイラーデー";
    	        case 9:
    	            return "換気の日";
    	        case 10:
    	            return "エレベーターの日";
    	        case 11:
    	            return "鏡の日";
    	        case 12:
    	            return "洋服記念日";
    	        case 13:
    	            return "うるしの日";
    	        case 14:
    	            return "パチンコの日";
    	        case 15:
    	            return "七五三";
    	        case 16:
    	            return "幼稚園記念日";
    	        case 17:
    	            return "将棋の日";
    	        case 18:
    	            return "土木の日";
    	        case 19:
    	            return "鉄道電化の日";
    	        case 20:
    	            return "ピザの日";
    	        case 21:
    	            return "インターネット記念日";
    	        case 22:
    	            return "大工さんの日";
    	        case 23:
    	            return "ゲームの日";
    	        case 24:
    	            return "鰹節の日";
    	        case 25:
    	            return "OLの日";
    	        case 26:
    	            return "ペンの日";
    	        case 27:
    	            return "ノーベル賞制定記念日";
    	        case 28:
    	            return "太平洋記念日";
    	        case 29:
    	            return "ダンスの日";
    	        case 30:
    	            return "年金の日";
    	    }
    	    break;
    	case 12:
    	    switch (intval(date_i18n("d"))) {
    	        case 1:
    	            return "カイロの日";
    	        case 2:
    	            return "原子炉の日";
    	        case 3:
    	            return "カレンダーの日";
    	        case 4:
    	            return "E.T.の日";
    	        case 5:
    	            return "厳島神社，原爆ドーム世界遺産登録日";
    	        case 6:
    	            return "姉の日";
    	        case 7:
    	            return "クリスマスツリーの日";
    	        case 8:
    	            return "事納め";
    	        case 9:
    	            return "障害者の日";
    	        case 10:
    	            return "ノーベル賞授与式";
    	        case 11:
    	            return "胃腸の日";
    	        case 12:
    	            return "漢字の日";
    	        case 13:
    	            return "美容室の日";
    	        case 14:
    	            return "南極の日";
    	        case 15:
    	            return "観光バス記念日";
    	        case 16:
    	            return "電話創業の日";
    	        case 17:
    	            return "飛行機の日";
    	        case 18:
    	            return "国連加盟記念日";
    	        case 19:
    	            return "日本初飛行の日";
    	        case 20:
    	            return "シーラカンスの日";
    	        case 21:
    	            return "バスケットボールの日";
    	        case 22:
    	            return "改正民法公布記念日";
    	        case 23:
    	            return "天皇誕生日";
    	        case 24:
    	            return "クリスマス・イヴ";
    	        case 25:
    	            return "クリスマス";
    	        case 26:
    	            return "プロ野球誕生の日";
    	        case 27:
    	            return "ピーターパンの日";
    	        case 28:
    	            return "身体検査の日";
    	        case 29:
    	            return "シャンソンの日";
    	        case 30:
    	            return "大納会";
    	        case 31:
    	            return "大晦日";
    	    }
    	    break;
    }
    return "unknown";
}

?>